### ISSUE TITLE
I'd like to help emulate iec and drives

### ISSUE THREAD

**Issue by sajattack** [kondrak/rust64#15]
I'd like to help emulate iec and disk/tape drives but I'm not sure exactly how you had planned to do it. I've looked through cia.rs, and I see you have iec_lines as a field in there. Does this represent a data byte or clock, data, and atn combined? I also noticed you have $DD00 marked TODO but I need a bit more guidance on how you were thinking of architecting this.  I'm a bit of a noob here but thought I'd see if you wanted help and could guide me in the right direction.

**Comment by kondrak** [comment]
Hi!
To be honest I haven't really done any thorough planning here. The entire project was just a means to see what can be done in Rust :) However, you are more than welcome to contribute if you feel like adding the drives!
The basic rule here would be to keep things in separate modules, so following the lead of cia.rs, vic.rs, etc. you could add tape.rs, iec.rs etc. respectively. The disk drive will be the most complex since it's virtually a second computer attached to a C64 (it has a 6502 CPU of it's own), so if you don't want to get discouraged too fast you could start looking at either mapping a cartdrige to proper ram sections (since .crt is not supported either at this point). Alternatively have a look at tape drive - it's quite trivial in comparison to disk drive and should be relatively easy to add.

Concerning $DD00 - the TODO was a note to myself to verify the functionality, this particular register has certain behaviors when reading/writing to it depending on the currently stored bit pattern and I haven't really gone through all of them so it's a high chance that it might be buggy. Clearly I never got to check it in the end, since it's been a while :)

**Comment by sajattack** [comment]
I thought $DD00 was iec-related and the TODO was because of that.

**Comment by kondrak** [comment]
Right, I forgot to address that in my previous comment - iec_lines was planned to store both clk and atn combined. When reading the cia2 $DD00 register, I was thinking about taking into account both cia2 AND 1541 iec_lines status (which I never got to implement), so that part is also missing in the //TODO section.

**Comment by sajattack** [comment]
I took your suggestion and am starting with cartridges.

**Comment by kondrak** [comment]
Data too, of course. Good luck with the cart!

**Comment by sajattack** [comment]
I got the most basic cartridges working (8k, load into ram at $8000). But more complicated, bank switching cartridges aren't working. Should I open a PR so we can look through it together and discuss it?
